### PR TITLE
Various bug fixes and added contrived benchmarks.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Contrived benchmarks aim to test edge-cases that invoke specific
algoritgms or worst-case possibilities for float parsing algorithms.
These are specific strings for near-halfway cases, with varying number
of digits, forcing use of the slowest algoritms.

- Updated abseil version to fix bug with <limits> missing.
- Change repository to the new home, `fastfloat/fast_float`.
- Avoid printing `bug` repeatedly if the parsed time is 0, and print it only once per test.

These changes are useful to test the changes in https://github.com/fastfloat/fast_float/pull/96. After benchmarking, the new benchmarks significantly outperform `strtod` in GCC for near-halfway cases with many digits, which (from what I remember) uses gmplib internally, which definitely highlights the improved performance. It also outperforms every other implementation.

### CODE REVIEW

**Comment by lemire** [comment]
Fantastic work!

**Comment by Alexhuszagh** [comment]
If you do run these benchmarks locally, I do recommend lowering the volume to 5,000-10,000, since some of these benchmarks run at ` 0.01 Mfloat/s` (netlib, 6400 digits for a denormal float), and can take quite a long time at the default number.

**Comment by lemire** [comment]
Ok. I might tweak the benchmark later to make sure it is reasonable.

**Comment by lemire** [comment]
Merging. I will adjust. Great stuff.

**Pull request merged**
